# Shared test fixtures (auto-sourced by testthat before the test files). One
# home for the bundled example workbook and its corrupted copy, plus a common
# skip guard for the openxlsx2 reader. Both workbooks are generated by the
# data-raw/make_workbooks.R script.

skip_if_no_openxlsx2 <- function() {
  testthat::skip_if_not_installed("openxlsx2")
}
skip_if_no_readxl <- skip_if_no_openxlsx2

# The filled example workbook (observations + locations + target sheets, with an
# instructions sheet).
example_wb <- function() {
  testthat::test_path("fixtures", "example.xlsx")
}

# A copy of the example with a broken observations sheet (unrecognized header +
# a non-numeric cell) that must fail validation.
corrupt_wb <- function() {
  testthat::test_path("fixtures", "example_corrupt.xlsx")
}
