# Shared test fixtures (auto-sourced by testthat before the test files). One
# home for the bundled example workbook, its corrupted copy, and the matching
# CSV directory, plus a common skip guard for the optional readxl reader. All of
# these are generated by data-raw/make_workbooks.R.

skip_if_no_readxl <- function() {
  testthat::skip_if_not_installed("readxl")
}

# The filled example workbook (observations + locations + target sheets, with an
# instructions sheet).
example_wb <- function() {
  testthat::test_path("fixtures", "example.xlsx")
}

# A copy of the example with a broken observations sheet (unrecognized header +
# a non-numeric cell) that must fail validation.
corrupt_wb <- function() {
  testthat::test_path("fixtures", "example_corrupt.xlsx")
}

# The same example as a directory of CSV inputs (observations.csv, locations.csv,
# target.csv), exercising the directory/CSV read path.
example_dir <- function() {
  testthat::test_path("fixtures", "example_dir")
}
